# Replace path with your wallpaper (or remove and let it fall back to black)
preload   = /usr/share/backgrounds/archlinux/archlinux-simplyblack.png
wallpaper = ,/usr/share/backgrounds/archlinux/archlinux-simplyblack.png
splash    = false
