general {
    hide_cursor = true
    grace = 0
    no_fade_in = false
}

background {
    monitor =
    color = rgba(20, 20, 28, 1.0)
}

input-field {
    monitor =
    size = 280, 55
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.4
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    halign = center
    valign = center
    position = 0, -100
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    font_size = 64
    halign = center
    valign = center
    position = 0, 100
}
